#+TITLE: Using Emacs and Org-Mode Publishing To Build Static Website
#+AUTHOR: Evgeniy N. Sharapov
#+DATE: <2021-07-18 Sun>

* Introduction
  
I have been using [[https://www.gnu.org/software/emacs/][Emacs]] since early 2000-s. Some years saw very heavy
and extensive use and some years were quite light. By no means I
consider myself an expert or even a pro when it comes to use and
configuring of [[https://www.gnu.org/software/emacs/][Emacs]]. It feels that this editor fell into obscurity
around mid 2000-s, but has been surging back to wider adoption. Which
leads to plenty of resources related to [[https://www.gnu.org/software/emacs/][Emacs]] on the internets. 

One feature of this editor, which attracts quite some number of new
users, is an [[https://orgmode.org/][Org Mode]]. To quote their web-site

#+begin_quote
Org mode is for keeping notes, maintaining to-do lists, planning
projects, authoring documents, computational notebooks, literate
programming and more — in a fast and effective plain text system.
#+end_quote

One of the things not mentioned here is ability of Org Mode to publish
or export notes from Org Mode format.

